add: ラクスル
corocn/paternity-leave-in-japan pull request #29
Opened 2021-06-16 04:54 UTC by childbamboo

ラクスルの情報を追加させていただきました。レビューお願いします！

2021-06-16 05:18 UTC, corocn requested changes

2021-06-16 05:18 UTC, corocn commented on README.md
> +| [ラクスル](https://recruit.raksul.com/) | ラクスル、ノバセル、ハコベル など | [here](https://recruit.raksul.com/story/archives/company/diversity/) | [あり](https://speakerdeck.com/raksulrecruiting/raksul-introduction?sl
> https://recruit.raksul.com/story/archives/company/diversity/

> 資料: 取得実績が確認できる記事や資料。Twitterでも良いです。ただし1記事、1ツイート内で社名と期間が確認できること。（Must）

こちらご確認ください

2021-06-16 06:00 UTC, childbamboo commented on README.md
> +| [ラクスル](https://recruit.raksul.com/) | ラクスル、ノバセル、ハコベル など | [here](https://recruit.raksul.com/story/archives/company/diversity/) | [あり](https://speakerdeck.com/raksulrecruiting/raksul-introduction?sl
ご確認ありがとうございます。

こちら、一覧へのリンクになりますが、対象記事は、一覧にある↓の記事です。
https://recruit.raksul.com/story/pdm-sasako/

一覧へのリンクを案内させていただいた理由ですが、この記事に加えて、もう1つ男性育休の記事がリリースされる予定だったため、そちらも目にしていただきたく一覧のURLを設定しました。

URLは個別記事へのリンクが良いでしょうか？

2021-06-16 11:31 UTC, corocn commented on README.md
> +| [ラクスル](https://recruit.raksul.com/) | ラクスル、ノバセル、ハコベル など | [here](https://recruit.raksul.com/story/archives/company/diversity/) | [あり](https://speakerdeck.com/raksulrecruiting/raksul-introduction?sl
はい！個別でお願いします！

2021-06-17 01:52 UTC, childbamboo commented on README.md
> +| [ラクスル](https://recruit.raksul.com/) | ラクスル、ノバセル、ハコベル など | [here](https://recruit.raksul.com/story/archives/company/diversity/) | [あり](https://speakerdeck.com/raksulrecruiting/raksul-introduction?sl
@corocn  https://recruit.raksul.com/story/pdm-sasako/ への差替え対応しました。確認お願いします！

2021-06-17 02:03 UTC, corocn approved these changes
@childbamboo azasu!!

2021-06-17 02:03 UTC, merged